[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["GigaHierz <lenahierzi@hotmail.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
mech-client = "^0.2.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
